[package]
name = "alina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.1"
clap = { version = "4.0.25", features = ["derive"] }
clipboard = "0.5.0"
ferris_print = "0.1.0"
